### ISSUE TITLE
1.18.2 version doesn't work

### ISSUE THREAD

**Issue by Heamaci** [Ladysnake/Pick-Your-Poison#1]
whenever i try to create a singleplayer world with this mod installed i get this error
![2022-03-21_19 15 24](https://user-images.githubusercontent.com/67716228/159394510-7c1800c6-89a4-4487-b0bc-58ab03b1d5a5.png)
r

**Comment by Lozf** [comment]
This happens to me, too.

**Comment by doctor4t** [comment]
Unless you send logs I can't help you.
