### ISSUE TITLE
Problem With Pick Your Poison

### ISSUE THREAD

**Issue by Jeddy01** [Ladysnake/Pick-Your-Poison#12]
Hi guys can you help me out when I am using the impaled mod with optifabric it's okay but when I put impaled and pick you poison it crashes it said that I don't have geckolib but when I download geckolib it keeps crashing but I didn't give me a fabric message that said incompatible mods, by the way, I'm in 1.19 I want to put impaled and pick your poison I've tried updating my java and fabric loader in on tlauncher also 1.19 version that's it

**Comment by AlejandroTheReal** [comment]
same

**Comment by ChaosDogG** [comment]
more than likely it's OptiFabric, OptiFine on it's own is EXTREMELY difficult to work around due to its closed-source nature and even then it's built for Forge, and making it work on Fabric brings in a WHOLE heap of issues more. I suggest finding alternatives to OF since there's a BUNCH available!

**Comment by Pyrofab** [comment]
That's because Pick Your Poison uses a library some custom shaders, which is not compatible with Optifine. I would advise looking for alternatives, there is a list here : https://github.com/LambdAurora/optifine_alternatives
