### ISSUE TITLE
im undead

### ISSUE THREAD

**Issue by Ghostblackout** [Ladysnake/Pick-Your-Poison#15]
so a friend and I was messing around in survival and then he tried to kill me when I had Numbness and then I became undead

**Comment by AternosBugsWithPoison** [comment]
live on dont try to come back

**Comment by AternosBugsWithPoison** [comment]
JK

**Comment by AternosBugsWithPoison** [comment]
u can come back

**Comment by Arathain** [comment]
**please do not spam issue comments.**
*also* the issue itself does not have any actual issue to bring forth.
