### ISSUE TITLE
Frogs Dont Show In /give Or Inventory

### ISSUE THREAD

**Issue by AternosBugsWithPoison** [Ladysnake/Pick-Your-Poison#20]
When I use the 2 mods needed geckolib and fabric api it doesnt work i used feather client and Aternos and it still didnt work

**Comment by AternosBugsWithPoison** [comment]
now you lose darts XD

**Comment by AternosBugsWithPoison** [comment]
wait no darts are no craftable

**Comment by Arathain** [comment]
please do not spam the issue comments.
