### ISSUE TITLE
[Suggestion] Some balance change suggestions

### ISSUE THREAD

**Issue by Gabo6480** [Ladysnake/Pick-Your-Poison#3]
Before anything, awesome mod, love the concept of the dart frogs and I feel like they bring a lot to Minecraft.
However I believe some parts of the mod completely break the balance of Minecraft's combat (And not in a fun way)

1- The poison-less darts are basically instantly throw-able punches on a stack that can be spammed with knockback, this makes them the best tool to deal damage to players while keeping them at a distance, which makes fighting against it very infuriating. In order to fix this I have the following suggestions:
     1.1- I would recommend removing the knockback, maybe reducing the damage they deal, and shortening their range (Since darts are mostly a medium to apply poison at a distance more than a lethal weapon after all).
     1.2- Add a dart blowpipe item in order to address the spamming issue, this item would behave similarly to a crossbow in the sense that you can pre-load it and store it in that state for near-instant use, however it would be almost instantly recharged with a right-click and have a slight cooldown after use. This will also allow players to have a slight chance to react when they see a player pull out the blowpipe.

2.- Being able to "milk" a dart frog infinitely is way too lenient, specially since darts are very cheap to craft. I would recommend that d-frogs should have a poisonous mucus coating that gets consumed when you use it to coat a dart or lick it in a bowl, this coating gets replenished after a couple seconds. This will help to nerf the poisoned dart production and the abuse of frog licking.

3.- Potion effects:
     3.1- Numbness: Way too lenient, you can achieve immortality by keeping the effect active by continuing to lick the frog, however, this will be somewhat addressed by the mucus-cooldown. Still nothing is stopping you form staggering a couple frogs to achieve the same effect. I don't know how would I fix this, other than replacing the effect entirely.
     3.2- Batrachotoxin: Bedrock poison but in Java, with the ability to kill. Would change it for anti-absorcion (aka reduce your max health temporarily).
     3.3- Comatose: Way too strong, and I completely despise how it robs you the ability to control your client (You can't even pause the game). Would recommend to replace it with a short stun (Forbidding you from moving and using items for it's duration), or an effect that forbids you from sprinting, jumping, shielding, attacking, and using tools/weapons. 

4.- Just make poisoned darts stackable, it feels very inconsistent not being able to, specially since potioned arrows can be stacked. I know you did this in order to limit their usage in a single combat, still, I would believe it wouldn't be that problematic in actual combat with the previous mentioned changes (It has to be tested though)

5.- Turn darts into a less effective early game variant for potioned arrows (aka make darts compatible with potion effects). Why not?

**Comment by Arathain** [comment]
1 and 2 I agree with - regarding 3, .1 is the point of the poison, it makes you essentially dependent on it
4. would make sense with 1 and 2
5. feels out-of-scope imo

**Comment by Xiribidus** [comment]
I agree with Arathain and am going to add that afaik you cannot get numbness from licking a frog while you have the effect, only from the darts making it more or less impossible to keep the effect going. Especially the first 2 sound great though
