### ISSUE TITLE
frogs giving the wrong effect in 1.20

### ISSUE THREAD

**Issue by portalmation** [Ladysnake/Pick-Your-Poison#34]
in pick your poison 1.20 the poison dart frogs give me the wrong effect and i am also get the wrong from when i shift right click them with a bowl the mods i have are fabric api, pick your poison, Geckolib and stain api

**Comment by Feu-Ghost** [comment]
To be more precise, it is probably linked to an error in the texture attribution, each frog spawn with a spawn egg are a type and a random Poison Dart Frog texture, when spawn from a bowl, the frog is more likely to have the good texture, even through it has still some wrong texture  (I had more mod but it is the same issues I believe)
